### ISSUE TITLE
Please mark the crate as deprecated on crates.io

### ISSUE THREAD

**Issue by psiphi75** [zesterer/coord-rs#13]
I've implemented this package and looked what it would take to add a couple of features.  I came to github and see it's intentionally no longer maintained.  Could you please label this package as deprecated on crates.io. Thanks.

**Comment by zesterer** [comment]
Hello. Cargo does not currently have a feature to specify deprecation. I will, however, push another release including such information in the README so that this will be visible when visiting the crate's page. Thanks for notifying me!
